// the fur color is just the color thats the most of the doggie I dont wanna make 2 since its more compicated and i rly dont wanna do that :P

const doggies = [
    {doggie1: '1', furColor: 'black', size: 'small'},
    {doggie1: '2', furColor: 'black', size: 'large'},
    {doggie1: '3', furColor: 'white', size: 'small'},
    {doggie1: '4', furColor: 'white', size: 'large'},
    {doggie1: '5', furColor: 'white', size: 'large'},
    {doggie1: '6', furColor: 'gray', size: 'small'},
    {doggie1: '7', furColor: 'gray', size: 'small'},
    {doggie1: '8', furColor: 'gray', size: 'small'},
    {doggie1: '9', furColor: 'white', size: 'small'},
    {doggie1: '10', furColor: 'white', size: 'small'}
]

const similarities = [
  {doggie1: '1', doggie2: '1', similarity: 'furColor & size'},
  {doggie1: '1', doggie2: '2', similarity: 'furColor'},
  {doggie1: '1', doggie2: '3', similarity: 'size'},
  {doggie1: '1', doggie2: '4', similarity: 'none'},
  {doggie1: '1', doggie2: '5', similarity: 'none'},
  {doggie1: '1', doggie2: '6', similarity: 'size'},
  {doggie1: '1', doggie2: '7', similarity: 'size'},
  {doggie1: '1', doggie2: '8', similarity: 'size'},
  {doggie1: '1', doggie2: '9', similarity: 'size'},
  {doggie1: '1', doggie2: '10', similarity: 'size'},

  {doggie1: '2', doggie2: '1', similarity: 'furColor'},
  {doggie1: '2', doggie2: '2', similarity: 'furColor & size'},
  {doggie1: '2', doggie2: '3', similarity: 'none'},
  {doggie1: '2', doggie2: '4', similarity: 'size & furColor'},
  {doggie1: '2', doggie2: '5', similarity: 'size & furColor'},
  {doggie1: '2', doggie2: '6', similarity: 'none'},
  {doggie1: '2', doggie2: '7', similarity: 'none'},
  {doggie1: '2', doggie2: '8', similarity: 'none'},
  {doggie1: '2', doggie2: '9', similarity: 'none'},
  {doggie1: '2', doggie2: '10', similarity: 'none'},

  {doggie1: '3', doggie2: '1', similarity: 'size'},
  {doggie1: '3', doggie2: '2', similarity: 'none'},
  {doggie1: '3', doggie2: '3', similarity: 'furColor & size'},
  {doggie1: '3', doggie2: '4', similarity: 'furColor'},
  {doggie1: '3', doggie2: '5', similarity: 'furColor'},
  {doggie1: '3', doggie2: '6', similarity: 'size'},
  {doggie1: '3', doggie2: '7', similarity: 'size'},
  {doggie1: '3', doggie2: '8', similarity: 'size'},
  {doggie1: '3', doggie2: '9', similarity: 'furColor & size'},
  {doggie1: '3', doggie2: '10', similarity: 'furColor & size'},

  {doggie1: '4', doggie2: '1', similarity: 'none'},
  {doggie1: '4', doggie2: '2', similarity: 'furColor & size'},
  {doggie1: '4', doggie2: '3', similarity: 'furColor'},
  {doggie1: '4', doggie2: '4', similarity: 'furColor & size'},
  {doggie1: '4', doggie2: '5', similarity: 'furColor & size'},
  {doggie1: '4', doggie2: '6', similarity: 'none'},
  {doggie1: '4', doggie2: '7', similarity: 'none'},
  {doggie1: '4', doggie2: '8', similarity: 'none'},
  {doggie1: '4', doggie2: '9', similarity: 'furColor'},
  {doggie1: '4', doggie2: '10', similarity: 'furColor'},

  {doggie1: '5', doggie2: '1', similarity: 'none'},
  {doggie1: '5', doggie2: '2', similarity: 'furColor & size'},
  {doggie1: '5', doggie2: '3', similarity: 'furColor'},
  {doggie1: '5', doggie2: '4', similarity: 'furColor & size'},
  {doggie1: '5', doggie2: '5', similarity: 'furColor & size'},
  {doggie1: '5', doggie2: '6', similarity: 'none'},
  {doggie1: '5', doggie2: '7', similarity: 'none'},
  {doggie1: '5', doggie2: '8', similarity: 'none'},
  {doggie1: '5', doggie2: '9', similarity: 'furColor'},
  {doggie1: '5', doggie2: '10', similarity: 'furColor'},

  {doggie1: '6', doggie2: '1', similarity: 'size'},
  {doggie1: '6', doggie2: '2', similarity: 'none'},
  {doggie1: '6', doggie2: '3', similarity: 'size'},
  {doggie1: '6', doggie2: '4', similarity: 'none'},
  {doggie1: '6', doggie2: '5', similarity: 'none'},
  {doggie1: '6', doggie2: '6', similarity: 'furColor & size'},
  {doggie1: '6', doggie2: '7', similarity: 'furColor & size'},
  {doggie1: '6', doggie2: '8', similarity: 'furColor & size'},
  {doggie1: '6', doggie2: '9', similarity: 'none'},
  {doggie1: '6', doggie2: '10', similarity: 'none'},

  {doggie1: '7', doggie2: '1', similarity: 'size'},
  {doggie1: '7', doggie2: '2', similarity: 'none'},
  {doggie1: '7', doggie2: '3', similarity: 'size'},
  {doggie1: '7', doggie2: '4', similarity: 'none'},
  {doggie1: '7', doggie2: '5', similarity: 'none'},
  {doggie1: '7', doggie2: '6', similarity: 'furColor & size'},
  {doggie1: '7', doggie2: '7', similarity: 'furColor & size'},
  {doggie1: '7', doggie2: '8', similarity: 'furColor & size'},
  {doggie1: '7', doggie2: '9', similarity: 'none'},
  {doggie1: '7', doggie2: '10', similarity: 'none'},

  {doggie1: '8', doggie2: '1', similarity: 'size'},
  {doggie1: '8', doggie2: '2', similarity: 'none'},
  {doggie1: '8', doggie2: '3', similarity: 'size'},
  {doggie1: '8', doggie2: '4', similarity: 'none'},
  {doggie1: '8', doggie2: '5', similarity: 'none'},
  {doggie1: '8', doggie2: '6', similarity: 'furColor & size'},
  {doggie1: '8', doggie2: '7', similarity: 'furColor & size'},
  {doggie1: '8', doggie2: '8', similarity: 'furColor & size'},
  {doggie1: '8', doggie2: '9', similarity: 'none'},
  {doggie1: '8', doggie2: '10', similarity: 'none'},

  {doggie1: '9', doggie2: '1', similarity: 'size'},
  {doggie1: '9', doggie2: '2', similarity: 'none'},
  {doggie1: '9', doggie2: '3', similarity: 'furColor & size'},
  {doggie1: '9', doggie2: '4', similarity: 'furColor'},
  {doggie1: '9', doggie2: '5', similarity: 'furColor'},
  {doggie1: '9', doggie2: '6', similarity: 'none'},
  {doggie1: '9', doggie2: '7', similarity: 'none'},
  {doggie1: '9', doggie2: '8', similarity: 'none'},
  {doggie1: '9', doggie2: '9', similarity: 'furColor & size'},
  {doggie1: '9', doggie2: '10', similarity: 'furColor & size'},

  {doggie1: '10', doggie2: '1', similarity: 'size'},
  {doggie1: '10', doggie2: '2', similarity: 'none'},
  {doggie1: '10', doggie2: '3', similarity: 'furColor & size'},
  {doggie1: '10', doggie2: '4', similarity: 'furColor'},
  {doggie1: '10', doggie2: '5', similarity: 'furColor'},
  {doggie1: '10', doggie2: '6', similarity: 'none'},
  {doggie1: '10', doggie2: '7', similarity: 'none'},
  {doggie1: '10', doggie2: '8', similarity: 'none'},
  {doggie1: '10', doggie2: '9', similarity: 'furColor & size'},
  {doggie1: '10', doggie2: '10', similarity: 'furColor & size'},
];

